# Generated by Django 4.2.14 on 2024-07-22 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='employee_type_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='paytype_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='provider_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 23, 27, 1, 696890)),
        ),
    ]
