# Generated by Django 4.2.14 on 2024-07-22 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments_amount_payments_employee_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 22, 23, 28, 23, 730726)),
        ),
    ]
