# Generated by Django 4.2.14 on 2024-07-24 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 0, 8, 34, 215690)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='provider_id',
            field=models.CharField(blank=True, default='A', max_length=10, null=True),
        ),
    ]
