# Generated by Django 4.2.14 on 2024-07-24 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payments_amount_alter_payments_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 1, 1, 4, 557311)),
        ),
    ]
