# Generated by Django 4.2.14 on 2024-07-24 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_payments_date_alter_payments_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 6, 38, 31, 615410)),
        ),
    ]
